# Fly.io 部署配置
app = "wechat-bot"
primary_region = "hkg"  # 香港区域，对中国用户延迟更低
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.checks]
    [http_service.checks.health]
      grace_period = "10s"
      interval = "30s"
      method = "GET"
      path = "/health"
      protocol = "http"
      timeout = "5s"
      tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[processes]
  app = "npm start"

[[mounts]]
  source = "data"
  destination = "/app/data"
  initial_size = "1gb"