[build]
# 构建命令
builder = "NIXPACKS"

[deploy]
# 启动命令
startCommand = "npm start"

# 健康检查
healthcheckPath = "/health"
healthcheckTimeout = 300

# 重启策略
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# 生产环境
NODE_ENV = "production"

# 端口配置（Railway会自动设置PORT环境变量）
# PORT = "3000"